name: Publish NuGet package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install GitVersion.Tool
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine version
        id: version
        run: dotnet-gitversion /output json > version.json

      - name: Set NuGet version environment variable
        run: echo "NUGET_VERSION=$(jq -r '.SemVer' version.json)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ChurnZero.Sdk/ChurnZero.Sdk.csproj

      - name: Build project
        run: dotnet build --configuration Release ChurnZero.Sdk/ChurnZero.Sdk.csproj

      - name: Create NuGet package
        run: dotnet pack --configuration Release ChurnZero.Sdk/ChurnZero.Sdk.csproj -p:PackageVersion=${{ env.NUGET_VERSION }}

      - name: Publish NuGet package
        run: dotnet nuget push ChurnZero.Sdk/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_VERSION: ${{ env.GitVersion_AssemblySemVer }}

